import os
import gzip
import re
from datetime import datetime
import pandas as pd
def extract_logs(folder_path):
    for filename in os.listdir(folder_path):
        if filename.endswith('.gz'):
            with gzip.open(os.path.join(folder_path, filename), 'rb') as f_in:
                extracted_filename = filename[:-3]
                count = 1
                while os.path.exists(os.path.join(folder_path, extracted_filename)):
                    extracted_filename = f"{filename[:-3]}_{count}"
                    count += 1
                with open(os.path.join(folder_path, extracted_filename), 'wb') as f_out:
                    f_out.write(f_in.read())
            os.remove(os.path.join(folder_path, filename))
def load_log_files(folder_path):
    import glob
    log_files = glob.glob(folder_path+"*.log*")
    logs = []
    for file in log_files:
        with open(file, "r") as f:
            for line in f:
                if "SIGTERM[soft,remote-exit]" in line or "Peer Connection Initiated with" in line or "SIGUSR1[soft,ping-restart]" in line:
                    logs.append(line)
    return logs

# fun fact, these 2 regexes were generated by GPT-4 and was almost flawless!
re_connected = re.compile(r'(?P<date>\w{3} \w{3} {1,2}\d{1,2} \d{2}:\d{2}:\d{2} \d{4}) (?P<ip>[\d.]+:\d+) \[(?P<user_name>[^\]]+)\] Peer Connection Initiated with')
re_disconnected = re.compile(r'(?P<date>\w{3} \w{3} {1,2}\d{1,2} \d{2}:\d{2}:\d{2} \d{4}) (?P<user_name>[\S]+)\/(?P<ip>[\d.]+:\d+)')

def extract_infos(row, status):
    if not row:
        return None
    date, ip, user = row.group('date'), row.group('ip'), row.group('user_name')
    dt = datetime.strptime(date, '%a %b %d %H:%M:%S %Y').strftime('%Y-%m-%d %H:%M:%S')
    return [status, dt, ip, user]

def regex(row):
    if "Peer Connection Initiated with" in row: search, status = re_connected.search(row), "Connected"
    if "] received" in row: search, status = re_disconnected.search(row), "Disconnected"
    if search:
        return extract_infos(search, status)

# get your openvpn logs from /var/log/openvpn/
folder_path = './openvpn/'
#extract_logs(folder_path)
logs = load_log_files(folder_path)
data = []
for row in logs:
    result = regex(row)
    if result is not None:
        data.append(result)

# Create DataFrame with extracted information
df = pd.DataFrame(data, columns=['status', 'datetime', 'ip', 'user'])
df['datetime'] = pd.to_datetime(df['datetime'])
df.sort_values(by=['datetime'], inplace=True)
df.to_csv('openvpn.csv', index=False)
df.to_excel('openvpn.xlsx', index=False)

# Below two functions wer also written by GPT-4!
def calculate_session_length(group):
    connected = group[group['status'] == 'Connected']
    disconnected = group[group['status'] == 'Disconnected']
    group['session_length'] = None

    for index, row in disconnected.iterrows():
        match = connected[(connected['ip'] == row['ip']) & (connected['datetime'] < row['datetime'])]
        if not match.empty:
            session_start = match.iloc[-1]['datetime']
            group.loc[index, 'session_length'] = row['datetime'] - session_start

    return group

def format_session_length(td):
    hours, remainder = divmod(td.seconds, 3600)
    minutes, seconds = divmod(remainder, 60)
    return f"{td.days * 24 + hours:02}:{minutes:02}:{seconds:02}"


df = df.groupby(['user']).apply(calculate_session_length)
df['session_length'] = df['session_length'].apply(lambda x: format_session_length(x) if pd.notnull(x) else x)
df.to_csv('openvpn_session_length.csv', index=False)

print("Done")
